# Generated by Django 3.1 on 2020-09-01 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conduc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=30)),
                ('nb_place', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.DateTimeField(verbose_name='dates')),
                ('arrive', models.DateTimeField(verbose_name='dates')),
                ('pri', models.IntegerField()),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_covoiturage.conduc')),
            ],
        ),
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=30)),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_covoiturage.trajet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
