# Generated by Django 3.1 on 2020-09-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_covoiturage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='arrive',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='depart',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
