# Generated by Django 3.1 on 2020-09-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_covoiturage', '0002_auto_20200902_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='arrive',
            field=models.DateTimeField(verbose_name="date d'arrivée"),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='depart',
            field=models.DateTimeField(verbose_name='date départ'),
        ),
    ]
