# Generated by Django 3.1 on 2020-09-02 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_covoiturage', '0003_auto_20200902_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='trajectoire',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
