# Generated by Django 3.1 on 2020-09-02 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_covoiturage', '0004_trajet_trajectoire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='trajectoire',
        ),
        migrations.AddField(
            model_name='trajet',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
