# Generated by Django 3.1 on 2020-09-03 03:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_covoiturage', '0005_auto_20200902_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trajet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
