# Generated by Django 3.1 on 2020-09-03 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_covoiturage', '0006_auto_20200903_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='lieu_arrive',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trajet',
            name='lieu_depart',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
